package com.anagrafica.db.mycontacts_db.entity.base;

/**
 * 
 * 
  _____                      _              _ _ _     _   _     _        __ _ _      
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |     
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___ 
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|
 
                                                                                   
 * DO NOT EDIT THIS FILE!! 
 *
 *  FOR CUSTOMIZE ContactBase PLEASE EDIT ../Contact.java
 * 
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER CODE GENERATION --
 * 
 */
 

/**
 * This is the model of Contact object
 * 
 */
 
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.math.BigDecimal;


import org.springframework.jdbc.core.RowMapper;
import com.anagrafica.db.mycontacts_db.entity.Contact;

public class ContactBase implements RowMapper<Contact>{
	
	private Long _id;
	
	// Attributes
    private String email;
    private String name;
    private String note;
    private String phone;
    private String surname;
	
	// Relations company
	private String company;
	
	
	
	@Override
	public Contact mapRow(ResultSet rs, int rowNum) throws SQLException {
		
		Contact obj = new Contact();
		try {
			obj.set_id(rs.getLong("id"));
			obj.setEmail(rs.getString("email"));
			obj.setName(rs.getString("name"));
			obj.setNote(rs.getString("note"));
			obj.setPhone(rs.getString("phone"));
			obj.setSurname(rs.getString("surname"));
			
        	
        	// Relations 1:m company
			obj.setCompany(rs.getString("company"));
        	
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		return obj;
	}


	public Long get_id() {
		return _id;
	}

	public void set_id(Long _id) {
		this._id = _id;
	}
	
	public String getEmail() {
		return email;
	}


	public void setEmail(String email) {
		this.email = email;
	}
	public String getName() {
		return name;
	}


	public void setName(String name) {
		this.name = name;
	}
	public String getNote() {
		return note;
	}


	public void setNote(String note) {
		this.note = note;
	}
	public String getPhone() {
		return phone;
	}


	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getSurname() {
		return surname;
	}


	public void setSurname(String surname) {
		this.surname = surname;
	}
	
    
    // Relations 1:m company
	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}
    
    
    
    
}